version: "3.8"

services:
  # PostgreSQL database
  db:
    image: postgres:13
    container_name: mnist_db
    restart: always
    environment:
      POSTGRES_DB: mnist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Streamlit web application
  web:
    build: .
    container_name: mnist_web
    restart: always
    depends_on:
      - db
    ports:
      - "8501:8501"
    volumes:
      - ./saved_models:/app/saved_models
    environment:
      - MODEL_PATH=/app/saved_models/mnist_classifier.pth
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mnist_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
