version: '3.8'

services:
  # Streamlit application
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mnist_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=master
      - MODEL_PATH=/app/saved_models/mnist_classifier.pth
    volumes:
      - ./saved_models:/app/saved_models
    depends_on:
      - db
    restart: always
    command: streamlit run streamlit/app.py --server.port=8501 --server.address=0.0.0.0

  # PostgreSQL database
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mnist_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=master
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
